module.exports = {
    "Dreame1CNoCloudRobot": require("./Dreame1CNoCloudRobot"),
    "Dreame1TNoCloudRobot": require("./Dreame1TNoCloudRobot"),
    "DreameD10SPlusNoCloudRobot": require("./DreameD10SPlusNoCloudRobot"),
    "DreameD10SProNoCloudRobot": require("./DreameD10SProNoCloudRobot"),
    "DreameD9ProPlusNoCloudRobot": require("./DreameD9ProPlusNoCloudRobot"),
    "DreameD9ProNoCloudRobot": require("./DreameD9ProNoCloudRobot"),
    "DreameD9NoCloudRobot": require("./DreameD9NoCloudRobot"),
    "DreameF9NoCloudRobot": require("./DreameF9NoCloudRobot"),
    "DreameL10ProNoCloudRobot": require("./DreameL10ProNoCloudRobot"),
    "DreameL10SProUltraHeatNoCloudRobot": require("./DreameL10SProUltraHeatNoCloudRobot"),
    "DreameL10SProNoCloudRobot": require("./DreameL10SProNoCloudRobot"),
    "DreameL10SUltraNoCloudRobot": require("./DreameL10SUltraNoCloudRobot"),
    "DreameL10UltraNoCloudRobot": require("./DreameL10UltraNoCloudRobot"),
	"DreameL40UltraNoCloudRobot": require("./DreameL40UltraNoCloudRobot"),
    "DreameMovaS20UltraNoCloudRobot": require("./DreameMovaS20UltraNoCloudRobot"),
    "DreameMovaZ500NoCloudRobot": require("./DreameMovaZ500NoCloudRobot"),
    "DreameP2148NoCloudRobot": require("./DreameP2148NoCloudRobot"),
    "DreameP2149NoCloudRobot": require("./DreameP2149NoCloudRobot"),
    "DreameP2150NoCloudRobot": require("./DreameP2150NoCloudRobot"),
    "DreameS10PlusNoCloudRobot": require("./DreameS10PlusNoCloudRobot"),
    "DreameW10ProNoCloudRobot": require("./DreameW10ProNoCloudRobot"),
    "DreameW10NoCloudRobot": require("./DreameW10NoCloudRobot"),
    "DreameX10PlusNoCloudRobot": require("./DreameX10PlusNoCloudRobot"),
	"DreameX40MasterNoCloudRobot": require("./DreameX40MasterNoCloudRobot"),
    "DreameX40UltraNoCloudRobot": require("./DreameX40UltraNoCloudRobot"),
    "DreameZ10ProNoCloudRobot": require("./DreameZ10ProNoCloudRobot"),
};
