title: NoCloud
description: >-
  Cloud replacement for vacuum robots enabling local-only operation
baseurl: ""
url: https://Valetudo.Cloud
github_username: DGAlexandru

plugins:
  - jekyll-seo-tag
collections:
  pages:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
