# Very similar to the release build.
# Feel free to merge those into a single yaml
{
  'name': 'Manual Build',
  'on': ['workflow_dispatch'],
  'jobs':
    {
      'build-NoCloud':
        {
          'runs-on': 'ubuntu-latest',
          'steps':
            [
              { 'uses': 'actions/checkout@v4' },
              {
                'name': 'Use Node.js 20.x',
                'uses': 'actions/setup-node@v4',
                'with': { 'node-version': '20.x' },
              },
              { 'name': 'Install', 'run': 'npm ci' },
              {
                'name': 'Generate OpenAPI Docs',
                'run': 'npm run build_openapi_schema',
              },
              {
                'name': 'Build NoCloud frontend',
                'run': 'npm run build --workspace=frontend',
              },
              {
                'name': 'Build NoCloud armv7',
                'run': 'npm run build_armv7 --workspace=backend',
              },
              {
                'name': 'Build NoCloud armv7 lowmem',
                'run': 'npm run build_armv7_lowmem --workspace=backend',
              },
              {
                'name': 'Build NoCloud aarch64',
                'run': 'npm run build_aarch64 --workspace=backend',
              },

              {
                'name': 'Upload armv7 build',
                'uses': 'actions/upload-artifact@v4',
                'with':
                  {
                    'name': 'NoCloud-armv7',
                    'path': './build/armv7/NoCloud',
                  },
              },
              {
                'name': 'Upload armv7 lowmem build',
                'uses': 'actions/upload-artifact@v4',
                'with':
                  {
                    'name': 'NoCloud-armv7-lowmem',
                    'path': './build/armv7/NoCloud-lowmem',
                  },
              },
              {
                'name': 'Upload aarch64 build',
                'uses': 'actions/upload-artifact@v4',
                'with':
                  {
                    'name': 'NoCloud-aarch64',
                    'path': './build/aarch64/NoCloud',
                  },
              },

              {
                'name': 'UPX-compress NoCloud binaries',
                'run': 'npm run upx',
              },
              {
                'name': 'Upload armv7 upx build',
                'uses': 'actions/upload-artifact@v4',
                'with':
                  {
                    'name': 'NoCloud-armv7.upx',
                    'path': './build/armv7/NoCloud.upx',
                  },
              },
              {
                'name': 'Upload armv7 lowmem upx build',
                'uses': 'actions/upload-artifact@v4',
                'with':
                  {
                    'name': 'NoCloud-armv7-lowmem.upx',
                    'path': './build/armv7/NoCloud-lowmem.upx',
                  },
              },
              {
                'name': 'Upload aarch64 upx build',
                'uses': 'actions/upload-artifact@v4',
                'with':
                  {
                    'name': 'NoCloud-aarch64.upx',
                    'path': './build/aarch64/NoCloud.upx',
                  },
              },

              {
                'name': 'Build manifest',
                'run': 'npm run build_release_manifest',
              },
              {
                'name': 'Upload manifest',
                'uses': 'actions/upload-artifact@v4',
                'with':
                  {
                    'name': 'NoCloud_release_manifest.json',
                    'path': './build/NoCloud_release_manifest.json',
                  },
              },
            ],
        },
    },
}
