# Automation of Nightly builds (similar to the release build) & upload to NoCloud nightly repository
name: Nightly build
on:
  schedule:
    - cron: 16 2 * * *
  workflow_dispatch:
jobs:
    nightly_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.x
    if: github.repository_owner == 'DGAlexandru'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Install NPM
        run: npm ci
      - name: Generate OpenAPI Docs
        run: npm run build_openapi_schema
      - name: Build NoCloud frontend
        run: npm run build --workspace=frontend
      - name: Build NoCloud
        run: npm run build --workspace=backend
      - name: UPX-compress NoCloud binaries
        run: npm run upx
      - name: Generate changelog
        run: npm run generate_nightly_changelog
      - name: Generate manifest
        run: npm run build_release_manifest nightly
      - name: Push generated files to Nightly repository
        id: push_directory
        uses: DGAlexandru/github-action-push-to-another-repository@v1.3
        env:
          SSH_DEPLOY_KEY: '${{ secrets.SSH_DEPLOY_KEY }}'
        with:
          source-directory: build
          destination-github-username: NoCloudBot
          destination-repository-name: NoCloud-nightly-builds
          destination-repository-username: DGAlexandru
          user-email: github_NoCloud_Nightly@yahoo.com
          target-branch: master

